version: "3.9"
services:
  RL4Quantum:
    image: nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04 # Macなら ubuntu20.04 etc.
    build:
      dockerfile: Docker/Dockerfile
      context: ..
    container_name: RL4Quantum
    hostname: RL4Quantum
    runtime: nvidia
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTHONDONTWRITEBYTECODE=1
      - TZ=Asia/Tokyo
    ports:
      - "6006:6006"
    volumes:
      - type: volume
        source: Notes
        target: /home/RL4Quantum/Notes
      - type: volume
        source: Result
        target: /home/RL4Quantum/Result
      - type: bind
        source: /tmp/.X11-unix # Macなら削除
        target: /tmp/.X11-unix # Macなら削除
    tty: true
    stdin_open: true

volumes:
  Notes:
    name: Notes
  Result:
    name: Result